name: Deploy Frontend

on: [push, pull_request]

env:
  TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@master

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Cache npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Error Message
        if: failure()
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ❗ Произошла ошибка во время установки зависимостей ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  lint:
    runs-on: ubuntu-latest
    needs: install-cache
    steps:
      - name: Checkout Commit
        uses: actions/checkout@master

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Restore npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Прогон линтера
        run: npm run lint

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Error Message
        if: failure()
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ❗ Произошла ошибка во время прогона линтера ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  unit-test:
    runs-on: ubuntu-latest
    needs: install-cache

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2

      - name: Установка Node.js
        uses: actions/setup-node@master
        with:
          node-version: 23

      - name: Restore npm dependencies
        uses: actions/cache@master
        id: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Прогон тестов
        run: npx vitest --coverage.enabled true

      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v2

      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@main
        if: failure()
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: ${{ github.job }}

      - name: Send Telegram Error Message
        if: failure()
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            ❗ Произошла ошибка во время прогона юнит тестов ❗
            
            🔹 Repo: ${{ github.repository }}
            🔹 Workflow: ${{ github.workflow }}
            🔹 Job: ${{ github.job }}
            
            🔗 Ссылка на джобу 🔗
            ${{ steps.jobs.outputs.html_url }}
            
            🔗 Ссылка на пайплайн 🔗
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  build:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: | 
            cd /home/energet/frontend && 
            git fetch && 
            echo '${{ github.ref_name }}'
            echo '${{ github.ref_name }}'
            git checkout ${{ github.ref_name }} && 
            git pull

      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          port: ${{ secrets.SERVER_PORT }}
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Source NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" # This loads nvm bash_completion
    
            cd /home/energet/frontend/ && nvm use && npm ci && npm run build

  notify-success:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Send Telegram Success Message
        uses: PacificPromise/macos-telegram-action@main
        with:
          type: topic
          message: |
            🔔 Frontend
            ✅ Изменения успешно задеплоены

            🔗 Ссылка на прод 🔗
            ${{ secrets.PRODUCTION_URL || 'Отсутствует' }}
